name: Update and Publish @noyobo/antd

on:
  schedule:
    - cron: '0 */4 * * *' # Run every 4 hours
  workflow_dispatch:

jobs:
  update-and-publish:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Login to npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Get current version of @noyobo/antd
        id: current-version
        run: echo "current_version=$(npm show @noyobo/antd version || echo '0.0.0')" >> $GITHUB_ENV

      - name: Get latest version of antd
        id: latest-version
        run: echo "latest_version=$(npm show antd version)" >> $GITHUB_ENV

      - name: Compare versions
        id: compare-versions
        run: |
          if [ "${{ env.current_version }}" != "${{ env.latest_version }}" ]; then
            echo "should_publish=true" >> $GITHUB_ENV
          else
            echo "should_publish=false" >> $GITHUB_ENV
          fi

      - name: Fetch antd package
        if: env.should_publish == 'true'
        run: |
          mkdir antd
          cd antd
          npm pack antd

      - name: Extract and modify package
        if: env.should_publish == 'true'
        run: |
          cd antd
          tar -xzf antd-*.tgz
          ls -al ./package
          sed -i '' 's/"name": "antd"/"name": "@noyobo\/antd"/' package/package.json
          sed -i '' '/"scripts": {/,/},/d' package/package.json
          cat package/package.json

      - name: Publish to scope @noyobo
        if: env.should_publish == 'true'
        run: |
          cd antd/package
          cat package.json
          npm whoami
          npm publish --access public

      - name: Latest version of @noyobo/antd
        if: env.should_publish == 'true'
        run: |
          version=$(npm show @noyobo/antd version)
          major_version=$(echo ${version} | cut -d '.' -f 1)
          npm dist-tag add @noyobo/antd@$version latest-$major_version
