name: Sync packages

on:
  schedule:
    - cron: '0 */12 * * 1-5'
  workflow_dispatch:

jobs:
  update-and-publish:
    runs-on: macos-latest

    strategy:
      matrix:
        package: [antd]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Login to npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Get current version of @noyobo/${{ matrix.package }}
        id: current-version
        run: echo "current_version=$(npm show @noyobo/${{ matrix.package }} version || echo '0.0.0')" >> $GITHUB_ENV

      - name: Get latest version of ${{ matrix.package }}
        id: latest-version
        run: |
          echo "latest_version=$(npm show ${{ matrix.package }} version)" >> $GITHUB_ENV
          echo "major_version=$(npm show ${{ matrix.package }} version | cut -d '.' -f 1)" >> $GITHUB_ENV

      - name: Compare versions
        id: compare-versions
        run: |
          if [ "${{ env.current_version }}" != "${{ env.latest_version }}" ]; then
            echo "should_publish=true" >> $GITHUB_ENV
          else
            echo "should_publish=false" >> $GITHUB_ENV
          fi

      - name: Fetch ${{ matrix.package }} package
        if: env.should_publish == 'true'
        run: |
          mkdir ${{ matrix.package }}
          cd ${{ matrix.package }}
          npm pack ${{ matrix.package }}

      - name: Extract and modify package
        if: env.should_publish == 'true'
        run: |
          cd ${{ matrix.package }}
          tar -xzf ${{ matrix.package }}-*.tgz
          ls -al ./package
          sed -i '' 's/"name": "${{ matrix.package }}"/"name": "@noyobo\/${{ matrix.package }}"/' package/package.json
          sed -i '' '/"scripts": {/,/},/d' package/package.json
          cat package/package.json

      - name: Publish to scope @noyobo
        if: env.should_publish == 'true'
        run: |
          cd ${{ matrix.package }}/package
          cat package.json
          npm whoami
          npm publish --access public
          npm dist-tag add @noyobo/${{ matrix.package }}@$latest_version latest-$major_version
